#!/bin/bash
#set -x
addToGit=no
partPatchesOnly=no
if [ "$1" = "-add-to-git" ]
then
  echo "Will add all patches to local git repo"
  addToGit=yes
  shift 1
fi
if [ "$1" = "-p" ]
then
  echo "Will only add part support patchfiles"
  partPatchesOnly=yes
  if [ "${addToGit}" = "yes" ]
  then
    echo "Error: Do not support adding part support patches to GIT"
    exit -1
  fi
  shift 1
fi
PKG=$1
VER=$2
shift 2
ADDITIONAL_PARTS=$*
TD=`pwd`

if [ ! -d ${TD}/patches/${PKG}-${VER} ]
then
  echo "No patches for this product"
  exit 0
fi
patchfiles=`/bin/ls ${TD}/patches/${PKG}-${VER}/*`
if [ "${partPatchesOnly}" == "yes" ]
then
  echo "Patching additional parts ${ADDITIONAL_PARTS}"
  patchfiles=""
else
  if [ ! -e ${TD}/patches/${PKG}-${VER} ] ; then
	echo "No patches dir."
	exit 0
  fi
fi
if [ ! -e ${TD}/src/${PKG}-${VER} ]; then
	echo "Source doesn't exist."; exit 1;
fi
cd ${TD}/src/${PKG}-${VER}
if [ "${addToGit}" = "yes" ]
then
  if [ ! -d .git ]
  then
    git init
    git add -A
    git commit -m "Initial clean sources"
  fi
fi
# Check to see if we want to add support for any extra parts in this build
# ADI Internal option. Not used in release builds
for addpart in ${ADDITIONAL_PARTS}
do
	if [ -d ${TD}/patches/part-support/${addpart}/${PKG}-${VER} ]
	then
		newPatchFiles="`/bin/ls ${TD}/patches/part-support/${addpart}/${PKG}-${VER}/*`"
		patchfiles+=" ${newPatchFiles}"
		echo "Will patch ${PKG} with ${newPatchFiles} to add support for ${addpart}"
                echo "P: ${patchfiles}"
	else
		echo "No patch file for adding part support for ${addpart} to ${PKG}"
	fi

done
echo "Patchfiles: ${patchfiles}"
for p in ${patchfiles}
do
	filename=$(basename $p)
	if [ ! -e ${TD}/src/${PKG}-${VER}/.${filename} ] ; then
	  patch -p1 --dry-run < $p > ${TD}/.patch.out 2>&1
	  if [ $? -ne 0 ] ; then
	    echo "Patch can't be applied."; cat ${TD}/.patch.out ; exit 1;
	  fi
	  echo "Applying: ${p}"
	  patch -p1 < $p
	  touch .${filename}
          if [ "${addToGit}" = "yes" ]
          then
            echo "Checking in patch to git"
            git add -A
            git commit -m "Applied patch $p"
          fi
	else
	  echo "${p} already applied.  Skipping."
	fi
	echo "Done Patching."
done
